services:
  app:
      image: gu1lh3rm3s0rd1/laravel
      container_name: app-laravel
      tty: true
      ports:
        - "9000:9000"
      volumes:
        - .:/var/www
      networks:
        - laravel
      depends_on:
        - db

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      # - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: hdc_events
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dockeruser
      MYSQL_PASSWORD: dockersenha
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
